/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SiparisGUI.java
 *
 * Created on 30.Kas.2011, 10:39:15
 */
package com.fenbilimleri.ogrencikayit;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;


public class DersDuzenleGUI extends javax.swing.JFrame {

    /** Creates new form SiparisGUI */
    public DersDuzenleGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDers = new javax.swing.JPanel();
        txtOgrenciID = new javax.swing.JTextField();
        lblGelenogrID = new javax.swing.JLabel();
        txtDERSALMATARIHI = new javax.swing.JTextField();
        lblDERSALMATARIHI = new javax.swing.JLabel();
        lblzorunlu1 = new javax.swing.JLabel();
        lblzorunlu2 = new javax.swing.JLabel();
        lblSecmeliDers = new javax.swing.JLabel();
        lblzorunlu3 = new javax.swing.JLabel();
        txtKredi = new javax.swing.JTextField();
        lblkredi = new javax.swing.JLabel();
        cbSecmeliDers = new javax.swing.JComboBox();
        lblzorunlu4 = new javax.swing.JLabel();
        cbZorunluDers1 = new javax.swing.JComboBox();
        cbZorunluDers3 = new javax.swing.JComboBox();
        cbZorunluDers4 = new javax.swing.JComboBox();
        cbZorunluDers2 = new javax.swing.JComboBox();
        btndersKaydet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ders Düzenle Formu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlDers.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtOgrenciID.setEnabled(false);
        txtOgrenciID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOgrenciIDActionPerformed(evt);
            }
        });

        lblGelenogrID.setText("Ogrenci ID");

        lblDERSALMATARIHI.setText("Ders Alma Tarihi");

        lblzorunlu1.setText("Zorunlu Ders 1");

        lblzorunlu2.setText("Zorunlu Ders 2");

        lblSecmeliDers.setText("Secmeli Ders");

        lblzorunlu3.setText("Zorunlu Ders 3");

        txtKredi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKrediKeyReleased(evt);
            }
        });

        lblkredi.setText("Toplam Kredi");

        cbSecmeliDers.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbSecmeliDersPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbSecmeliDers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbSecmeliDersKeyReleased(evt);
            }
        });

        lblzorunlu4.setText("Zorunlu Ders 4");

        cbZorunluDers1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbZorunluDers1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbZorunluDers1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbZorunluDers1KeyReleased(evt);
            }
        });

        cbZorunluDers3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbZorunluDers3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbZorunluDers3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbZorunluDers3KeyReleased(evt);
            }
        });

        cbZorunluDers4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbZorunluDers4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbZorunluDers4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbZorunluDers4KeyReleased(evt);
            }
        });

        cbZorunluDers2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbZorunluDers2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbZorunluDers2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbZorunluDers2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlDersLayout = new javax.swing.GroupLayout(pnlDers);
        pnlDers.setLayout(pnlDersLayout);
        pnlDersLayout.setHorizontalGroup(
            pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDersLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblzorunlu2)
                            .addComponent(lblzorunlu1)
                            .addComponent(lblzorunlu3)
                            .addComponent(lblzorunlu4)
                            .addComponent(lblSecmeliDers))
                        .addGap(57, 57, 57)
                        .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDersLayout.createSequentialGroup()
                                .addComponent(cbZorunluDers1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbSecmeliDers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlDersLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(cbZorunluDers4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDersLayout.createSequentialGroup()
                        .addComponent(lblkredi)
                        .addGap(57, 57, 57)
                        .addComponent(txtKredi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbZorunluDers2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbZorunluDers3, javax.swing.GroupLayout.Alignment.TRAILING, 0, 309, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDersLayout.createSequentialGroup()
                        .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGelenogrID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDERSALMATARIHI, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60)
                        .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDERSALMATARIHI)
                            .addComponent(txtOgrenciID))))
                .addContainerGap())
        );
        pnlDersLayout.setVerticalGroup(
            pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOgrenciID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGelenogrID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDERSALMATARIHI)
                    .addComponent(txtDERSALMATARIHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbZorunluDers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblzorunlu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbZorunluDers2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblzorunlu2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbZorunluDers3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblzorunlu3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblzorunlu4)
                    .addComponent(cbZorunluDers4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSecmeliDers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecmeliDers))
                .addGap(38, 38, 38)
                .addGroup(pnlDersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkredi)
                    .addComponent(txtKredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btndersKaydet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndersKaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Speech-Bubble-add.png"))); // NOI18N
        btndersKaydet.setText("Kaydet");
        btndersKaydet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndersKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndersKaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(btndersKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndersKaydet)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection baglanti = null;
    ResultSet resultSet = null;
    PreparedStatement preparedStatement = null;
  
    
    
private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    baglanti = oraclebaglantisi.Baglan();
    acilirderslerisecmeliderslerledoldur();
    acilirderslerizorunluderslerledoldur();
    txtOgrenciID.setText(KullaniciFormuGUI.ogr_id.toString());
}//GEN-LAST:event_formWindowOpened

    private void txtOgrenciIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOgrenciIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOgrenciIDActionPerformed

    private void txtKrediKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKrediKeyReleased

    }//GEN-LAST:event_txtKrediKeyReleased

    private void cbSecmeliDersPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbSecmeliDersPopupMenuWillBecomeInvisible
        krediHesaplayanMetod();
    }//GEN-LAST:event_cbSecmeliDersPopupMenuWillBecomeInvisible

    private void cbSecmeliDersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbSecmeliDersKeyReleased
        krediHesaplayanMetod();
    }//GEN-LAST:event_cbSecmeliDersKeyReleased

    private void cbZorunluDers1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbZorunluDers1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers1PopupMenuWillBecomeInvisible

    private void cbZorunluDers1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbZorunluDers1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers1KeyReleased

    private void cbZorunluDers3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbZorunluDers3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers3PopupMenuWillBecomeInvisible

    private void cbZorunluDers3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbZorunluDers3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers3KeyReleased

    private void cbZorunluDers4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbZorunluDers4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers4PopupMenuWillBecomeInvisible

    private void cbZorunluDers4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbZorunluDers4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers4KeyReleased

    private void cbZorunluDers2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbZorunluDers2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers2PopupMenuWillBecomeInvisible

    private void cbZorunluDers2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbZorunluDers2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZorunluDers2KeyReleased

    private void btndersKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndersKaydetActionPerformed
        kaydetNormalYolla2();
    }//GEN-LAST:event_btndersKaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DersDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DersDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DersDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DersDuzenleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndersKaydet;
    private javax.swing.JComboBox cbSecmeliDers;
    private javax.swing.JComboBox cbZorunluDers1;
    private javax.swing.JComboBox cbZorunluDers2;
    private javax.swing.JComboBox cbZorunluDers3;
    private javax.swing.JComboBox cbZorunluDers4;
    private javax.swing.JLabel lblDERSALMATARIHI;
    private javax.swing.JLabel lblGelenogrID;
    private javax.swing.JLabel lblSecmeliDers;
    private javax.swing.JLabel lblkredi;
    private javax.swing.JLabel lblzorunlu1;
    private javax.swing.JLabel lblzorunlu2;
    private javax.swing.JLabel lblzorunlu3;
    private javax.swing.JLabel lblzorunlu4;
    private javax.swing.JPanel pnlDers;
    private javax.swing.JTextField txtDERSALMATARIHI;
    private javax.swing.JTextField txtKredi;
    public javax.swing.JTextField txtOgrenciID;
    // End of variables declaration//GEN-END:variables

    private void acilirderslerisecmeliderslerledoldur() {

        try {
            preparedStatement = baglanti.prepareStatement("SELECT * FROM SECIM_SECMELI");
            resultSet = preparedStatement.executeQuery();

            cbSecmeliDers.addItem("");//İLK KAYDINIZ
            while (resultSet.next()) {
                String SECMELIDERSADI = resultSet.getString("SECMELIDERSADI");
                cbSecmeliDers.addItem(SECMELIDERSADI);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "HATA1 : " + e, "MESAJ", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void acilirderslerizorunluderslerledoldur() {

        try {
            preparedStatement = baglanti.prepareStatement("SELECT * FROM SECIM_ZORUNLU");
            resultSet = preparedStatement.executeQuery();

            cbZorunluDers1.addItem("");//İLK KAYDINIZ
            cbZorunluDers3.addItem("");
            cbZorunluDers4.addItem("");
            cbZorunluDers2.addItem("");
            while (resultSet.next()) {
                String URUNADI = resultSet.getString("ZORUNLUDERSADI");
                cbZorunluDers1.addItem(URUNADI);
                cbZorunluDers3.addItem(URUNADI);
                cbZorunluDers4.addItem(URUNADI);
                cbZorunluDers2.addItem(URUNADI);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "HATA1 : " + e, "MESAJ", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void krediHesaplayanMetod() {
        try {
            preparedStatement = baglanti.prepareStatement("SELECT * FROM SECIM_SECMELI WHERE SECMELIDERSADI = ?");
            preparedStatement.setString(1, cbSecmeliDers.getSelectedItem().toString());
            resultSet = preparedStatement.executeQuery();

            while (resultSet.next()) {
String a;
                a=resultSet.getString("ZORUNLUDERSKREDI");
                
                       

               txtKredi.setText(String.valueOf(Double.parseDouble(a)));
   }

        } catch (Exception e) {

        }

    }

   private void kaydetNormalYolla2() {
 
        try {

            String eklemeSorgusu = "UPDATE DERS   "
                    + "SET DERSID = '"+txtOgrenciID.getText()+"'"
                    + ",DERSALMATARIHI = '"+txtDERSALMATARIHI.getText()+"'"
                    + ",ZORUNLUDERS1 = '"+cbZorunluDers1.getSelectedItem().toString()+"' "
                    + ",ZORUNLUDERS2 = '"+cbZorunluDers3.getSelectedItem().toString()+"' "
                    + ",ZORUNLUDERS3 = '"+cbZorunluDers4.getSelectedItem().toString()+"' "     
                    + ",ZORUNLUDERS4 = '"+cbZorunluDers2.getSelectedItem().toString()+"' "
                    + ",SECMELIDERS1 = '"+cbSecmeliDers.getSelectedItem().toString()+"' "
                    + ",TOPLAMKREDI = '"+txtKredi.getText()+"'      "
                    + " WHERE OGRENCIID = '"+txtOgrenciID.getText()+"'";
            preparedStatement = baglanti.prepareStatement(eklemeSorgusu);

         
            preparedStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Güncellenme işlemi\nbaşarılı olarak gerçekleştirildi.", "MESAJ",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "HATA :" + e, "MESAJ", JOptionPane.ERROR_MESSAGE);

        }

        
        
        
    }


    private void dersFormunuTemizle() {

        txtDERSALMATARIHI.setText(null);
        cbZorunluDers1.setSelectedIndex(0);
        cbZorunluDers3.setSelectedIndex(0);
        cbZorunluDers4.setSelectedIndex(0);
        cbZorunluDers2.setSelectedIndex(0);
        cbSecmeliDers.setSelectedIndex(0);
        txtKredi.setText("");
    }
}
